project_id = "abobvpamaiwrgwtghoyh"

[functions.scan-comments]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-login-link]
verify_jwt = true

[functions.auth-rate-limit]
verify_jwt = false

[functions.thematic-analysis]
verify_jwt = false
