// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abobvpamaiwrgwtghoyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFib2J2cGFtYWl3cmd3dGdob3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTA5NDAsImV4cCI6MjA3MDAyNjk0MH0.4EnP4lkkvhYySkkAK80dc4dmqoHrBvfm6Ql0hzdtdy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});